---
########################################
# Prep
default:
  # specify runner tags to execute all jobs on (these need to match tags on the runner)
  # even though some jobs (begin/end) don't need docker, they still need a tag so that
  # a runner schedules them properly.
  # $DOCKER_REGISTRY is defined in the local runner's in the runner config toml
  image: $DOCKER_REGISTRY/rockylinux8-puppet7:latest
  tags:
    - puppet_runner

  before_script: &before_script
    - bundle -v
    - rm Gemfile.lock || true
    - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
    - "# Set `rubygems_version` in the .sync.yml to set a value"
    - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
    - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
    - gem --version
    - bundle -v
    - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - vendor/bundle

stages:
  - PDK Validate
  - Lint Check
  - Puppet Spec Tests

########################################
# jobs

PDK Validate:
  stage: PDK Validate
  script:
    - pdk validate --parallel
  variables:
    PUPPET_GEM_VERSION: '~> 7'

Lint Check:
  stage: Lint Check
  script:
    - bundle exec rake validate lint check rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 7'

Puppet Spec Tests:
  stage: Puppet Spec Tests
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 7'

